# Generated by Django 5.0.7 on 2024-07-17 19:10

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sage_mailbox", "0002_alter_mailbox_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="headers",
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
