
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-01T08:21:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "92efe6ae2d28bc648d16f1283629c3599a2cbb7a",
 "version": "5.4.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
