path=input('py文件路径：')
file=open(path,'r',encoding='utf-8')
rd=file.read()
file.close()
file=open(path,'w',encoding='utf-8')
file.seek(0)
file.write('\n')
file.seek(0)
file.write('from paddy import *\ndef 您的函数名(参数名):\n\t#您想要执行的内容')
file.close()
file=open(path,'a',encoding='utf-8')
file.write(rd)
file.close()