# generated by datamodel-codegen:
#   filename:  HelloAssoV5OpenAPI.json
#   timestamp: 2024-04-28T15:09:13+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel

from helloasso_api_wrapper.models import common, enums, statistics


class PublicPaymentModel(BaseModel):
    id: int | None = None
    organizationId: int | None = None
    formId: int | None = None
    formType: enums.FormType | None = None
    amount: int | None = None
    meansPayment: enums.PaymentMeans | None = None
    cashOutState: enums.PaymentCashOutState | None = None
    date: datetime | None = None
    authorizationDate: datetime | None = None
    orderDate: datetime | None = None
    orderId: int | None = None
    fiscalReceiptGenerated: bool | None = None
    payerFirstName: str | None = None
    payerLastName: str | None = None
    status: enums.PaymentState | None = None
    userId: int | None = None
    userFirstName: str | None = None
    userLastName: str | None = None
    userEmail: str | None = None
    providerTitle: str | None = None
    installmentNumber: int | None = None
    meta: common.MetaModel | None = None
    refundOperations: list[statistics.RefundOperationLightModel] | None = None
