# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightwind/inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19lightwind/inference.proto\x12\x18\x63om.webank.rpc.lightwind\"\x9b\x01\n\x07Inbound\x12\x41\n\x08metadata\x18\x01 \x03(\x0b\x32/.com.webank.rpc.lightwind.Inbound.MetadataEntry\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaf\x01\n\x08Outbound\x12\x42\n\x08metadata\x18\x01 \x03(\x0b\x32\x30.com.webank.rpc.lightwind.Outbound.MetadataEntry\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32j\n\x17PrivateTransferProtocol\x12O\n\x06invoke\x12!.com.webank.rpc.lightwind.Inbound\x1a\".com.webank.rpc.lightwind.Outboundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lightwind.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INBOUND_METADATAENTRY']._loaded_options = None
  _globals['_INBOUND_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_OUTBOUND_METADATAENTRY']._loaded_options = None
  _globals['_OUTBOUND_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INBOUND']._serialized_start=56
  _globals['_INBOUND']._serialized_end=211
  _globals['_INBOUND_METADATAENTRY']._serialized_start=164
  _globals['_INBOUND_METADATAENTRY']._serialized_end=211
  _globals['_OUTBOUND']._serialized_start=214
  _globals['_OUTBOUND']._serialized_end=389
  _globals['_OUTBOUND_METADATAENTRY']._serialized_start=164
  _globals['_OUTBOUND_METADATAENTRY']._serialized_end=211
  _globals['_PRIVATETRANSFERPROTOCOL']._serialized_start=391
  _globals['_PRIVATETRANSFERPROTOCOL']._serialized_end=497
# @@protoc_insertion_point(module_scope)
