
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-05T15:29:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a53509555d6d83b0efd99d98fc2bcd74d7e98eb",
 "version": "2024.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
