"""
DirectAdmin supported endpoints.
"""

# Admin Endpoints
GET_ALL_USERS = "CMD_API_SHOW_ALL_USERS"
GET_ALL_ADMINS = "CMD_API_SHOW_ADMINS"
GET_ALL_RESELLERS = "CMD_API_SHOW_RESELLERS"
GET_ADMIN_STATS = "CMD_API_ADMIN_STATS"
CREATE_ADMIN_ACCOUNT = "CMD_ACCOUNT_ADMIN"

# Reseller Endpoint
GET_RESELLER_PACKAGES = "CMD_API_PACKAGES_RESELLER"
GET_RESELLER_IP_LIST = "CMD_API_SHOW_RESELLER_IPS"
CREATE_RESELLER_ACCOUNT = "CMD_ACCOUNT_RESELLER"

# User Endpoints
GET_USER_PACKAGES = "CMD_API_PACKAGES_USER"
GET_USER_CONFIG = "CMD_API_SHOW_USER_CONFIG"
GET_USER_USAGE = "CMD_API_SHOW_USER_USAGE"
GET_USER_DOMAIN = "CMD_API_SHOW_USER_DOMAINS"
CREATE_USER_ACCOUNT = "CMD_API_ACCOUNT_USER"
