# Generated by Django 5.0.6 on 2024-08-01 17:33

import django_redis_pull.models.pull_log
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PullLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=255)),
                ("count", models.IntegerField()),
                (
                    "created_at",
                    models.IntegerField(
                        default=django_redis_pull.models.pull_log.get_timestamp
                    ),
                ),
            ],
            options={
                "db_table": "redis_pull_log",
            },
        ),
        migrations.CreateModel(
            name="PullQueue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "redis_pull_queue",
            },
        ),
        migrations.CreateModel(
            name="PullData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=255)),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "redis_pull_data",
                "indexes": [
                    models.Index(fields=["queue"], name="redis_pull__queue_1f8e69_idx")
                ],
            },
        ),
    ]
