
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-05T20:05:07+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f2d8c2b3d574c5f2d58492c90997a8c4fa84b60",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
