
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-05T11:58:50+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "111299317120411f407b015b2b7dbf8402aa35c8",
 "version": "0.14.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
