# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.concrete_block_check_res_data_idea_stati_ca_connection_checks import ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks

class TestConcreteBlockCheckResDataIdeaStatiCaConnectionChecks(unittest.TestCase):
    """ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks:
        """Test ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks`
        """
        model = ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks()
        if include_optional:
            return ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks(
                fjd = 1.337,
                average_stress = 1.337,
                nsd = 1.337,
                aeff = 1.337,
                aeff_center_gravity = '',
                center_tension = '',
                center_compression = '',
                aeff2 = 1.337,
                supporting_regions = [
                    connection_restapi_client_poc.models.ci_geometry2_d_i_region2_d_ci_basic_types.CI_Geometry2D_IRegion2D-CI_BasicTypes(
                        outline = connection_restapi_client_poc.models.ci_geometry2_d_i_poly_line2_d_ci_basic_types.CI_Geometry2D_IPolyLine2D-CI_BasicTypes(
                            start_point = connection_restapi_client_poc.models.ci_geometry2_d_ida_com_point2_d_ci_basic_types.CI_Geometry2D_IdaComPoint2D-CI_BasicTypes(
                                x = 1.337, 
                                y = 1.337, ), 
                            is_closed = True, 
                            segments = [
                                connection_restapi_client_poc.models.ci_geometry2_d_i_segment2_d_ci_basic_types.CI_Geometry2D_ISegment2D-CI_BasicTypes(
                                    end_point = connection_restapi_client_poc.models.ci_geometry2_d_ida_com_point2_d_ci_basic_types.CI_Geometry2D_IdaComPoint2D-CI_BasicTypes(
                                        x = 1.337, 
                                        y = 1.337, ), )
                                ], 
                            length = 1.337, 
                            bounds = '', 
                            id = 56, ), 
                        openings = [
                            connection_restapi_client_poc.models.ci_geometry2_d_i_poly_line2_d_ci_basic_types.CI_Geometry2D_IPolyLine2D-CI_BasicTypes(
                                is_closed = True, 
                                length = 1.337, 
                                bounds = '', 
                                id = 56, )
                            ], 
                        arc_discr_angle = 1.337, )
                    ],
                aeff_net = 1.337,
                unity_check_stress = 1.337,
                kj = 1.337,
                add_bearing_width = 1.337,
                eff_area_of_base_plates = {
                    'key' : [
                        [
                            [
                                connection_restapi_client_poc.models.ci_gi_cl2_d_path2_d_segment_ci_geometry2_d.CI_GiCL2D_Path2D_Segment-CI_Geometry2D(
                                    end = '', )
                                ]
                            ]
                        ]
                    },
                gamma_c = 1.337,
                fck = 1.337,
                fck_factored = 1.337,
                betaj = 1.337,
                alpha_cc = 1.337,
                fc = 1.337,
                phi_crt = 1.337,
                omega_crt = 1.337,
                fck_ext1 = 1.337,
                fck_ext2 = 1.337,
                fck_ext = 1.337,
                crt_bearing_strength = 1.337,
                phi_c = 1.337,
                psi_snip = 1.337,
                phi_b_snip = 1.337,
                gamma_b_snip = 1.337,
                beta_c_chn = 1.337,
                beta_l_chn = 1.337,
                reinforced_concrete_pad = True,
                omega_factor = 1.337,
                crt_comp_check_is = 'iS800_Cl_7_4',
                gamma_m0_is = 1.337,
                base_plate_thickness = 1.337,
                base_plate_fy = 1.337,
                eff_area_offset = 1.337,
                concrete_grade = '',
                id = 56,
                name = '',
                check_status = True,
                limit_check_status = True,
                load_case_id = 56,
                load_case = '',
                max_unity_check = 1.337,
                form = ''
            )
        else:
            return ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks(
        )
        """

    def testConcreteBlockCheckResDataIdeaStatiCaConnectionChecks(self):
        """Test ConcreteBlockCheckResDataIdeaStatiCaConnectionChecks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
