# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.data_check_outcome_ci_basic_types import DataCheckOutcomeCIBasicTypes

class TestDataCheckOutcomeCIBasicTypes(unittest.TestCase):
    """DataCheckOutcomeCIBasicTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataCheckOutcomeCIBasicTypes(self):
        """Test DataCheckOutcomeCIBasicTypes"""
        # inst = DataCheckOutcomeCIBasicTypes()

if __name__ == '__main__':
    unittest.main()
