# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.api.material_api import MaterialApi


class TestMaterialApi(unittest.TestCase):
    """MaterialApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MaterialApi()

    def tearDown(self) -> None:
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_bolt_assemblies_get(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_bolt_assemblies_get

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_bolt_assemblies_post(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_bolt_assemblies_post

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_cross_sections_get(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_cross_sections_get

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_cross_sections_post(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_cross_sections_post

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_get(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_get

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_pins_get(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_pins_get

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_pins_post(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_pins_post

        """
        pass

    def test_api1_projects_project_id_connections_connection_id_materials_post(self) -> None:
        """Test case for api1_projects_project_id_connections_connection_id_materials_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
