# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .status_types import StatusTypes


class Status(UniversalBaseModel):
    status: StatusTypes
    pod_ip: str = pydantic.Field(alias="podIp")
    host_ip: str = pydantic.Field(alias="hostIp")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
