# coding: utf-8

"""
    OpenPay API

    super charge your subscription management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import re  # noqa: F401
from enum import Enum

try:
  from typing import Self
except ImportError:
  from typing_extensions import Self


class CreditCardType(str, Enum):
  """
    CreditCardType
    """
  """
    allowed enum values
    """
  VISA = 'visa'
  MASTERCARD = 'mastercard'
  AMERICAN_EXPRESS = 'american_express'
  JCB = 'jcb'
  DISCOVER = 'discover'
  ENROUTE = 'enroute'
  UNIONPAY = 'unionpay'
  PAYPAL = 'paypal'
  DINERS_CLUB = 'diners_club'
  MIR = 'mir'
  EFTPOS_AUSTRALIA = 'eftpos_australia'
  ECHECK_DOT_NET = 'echeck.net'
  OTHER = 'other'

  @classmethod
  def from_json(cls, json_str: str) -> Self:
    """Create an instance of CreditCardType from a JSON string"""
    return cls(json.loads(json_str))
