# generated by datamodel-codegen:
#   filename:  HelloAssoV5OpenAPI.json
#   timestamp: 2024-04-28T15:09:13+00:00

from __future__ import annotations

from pydantic import BaseModel

from helloasso_api_wrapper.models import enums


class InternalTagModel(BaseModel):
    id: int | None = None
    name: str | None = None
    formCount: int | None = None
    organizationCount: int | None = None
    tagType: enums.TagType | None = None
    tagParent: InternalTagModel | None = None
    amountCollected: int | None = None


class PublicTagModel(BaseModel):
    name: str | None = None
    score: float | None = None


InternalTagModel.update_forward_refs()
