import pandas as pd


class FiinIndicator:
    def ema(self, col: pd.Series, window: int) -> pd.Series: ...
        
    def sma(self, col: pd.Series, window: int) -> pd.Series: ...
        
    def rsi(self, col: pd.Series, window: int = 14) -> pd.Series: ...

    def macd(self, col: pd.Series, window_slow: int = 26, window_fast: int = 12) -> pd.Series: ...
    
    def macd_signal(self, col: pd.Series, window_slow: int = 26, window_fast: int = 12, window_sign: int = 9) -> pd.Series: ...
        
    def macd_diff(self, col: pd.Series, window_slow: int = 26, window_fast: int = 12, window_sign: int = 9) -> pd.Series: ...

    def bollinger_mavg(self, col: pd.Series, window: int = 20) -> pd.Series: ...

    def bollinger_std(self, col: pd.Series, window: int = 20) -> pd.Series: ...

    def bollinger_hband(self, col: pd.Series, window: int = 20, window_dev = 2) -> pd.Series: ...

    def bollinger_lband(self, col: pd.Series, window: int = 20, window_dev = 2) -> pd.Series: ...
       
    def stoch(self, low: pd.Series, high: pd.Series, close: pd.Series, window: int = 14) -> pd.Series: ...
    
    def stoch_signal(self, low: pd.Series, high: pd.Series, close: pd.Series, window: int = 14, smooth_window: int = 3) -> pd.Series: ...
        