# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clahe_img": "core.ipynb",
         "CorrespondenceAnnotator": "core.ipynb",
         "optimize_points_H": "deephelp.ipynb",
         "optimize_points_H_hardnet": "deephelp.ipynb",
         "get_bbox": "imgproc.ipynb",
         "overlay_common_area": "imgproc.ipynb",
         "draw_epipolar_lines": "imgproc.ipynb",
         "clip_corrs": "imgproc.ipynb",
         "get_model": "imgproc.ipynb",
         "draw_homography": "imgproc.ipynb",
         "tilt_image": "imgproc.ipynb",
         "rectify_plane": "imgproc.ipynb",
         "imread": "io.ipynb",
         "load_pts": "io.ipynb",
         "leave_one_out_F_validation": "metrics.ipynb",
         "leave_one_out_H_validation": "metrics.ipynb",
         "get_error_stat_string": "metrics.ipynb",
         "get_big_errors_string": "metrics.ipynb"}

modules = ["core.py",
           "deephelp.py",
           "imgproc.py",
           "io.py",
           "metrics.py"]

doc_url = "https://ducha-aiki.github.io/pixelstitch/"

git_url = "https://github.com/ducha-aiki/pixelstitch/tree/master/"

def custom_doc_links(name): return None
