
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-04T14:15:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b69b375bb68c53e20b824b4579fb5146766c626a",
 "version": "1.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
