# Generated by Django 4.2 on 2024-07-20 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_jwt', '0002_alter_customtoken_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 12, 20, 30, 250220, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 12, 20, 30, 250220, tzinfo=datetime.timezone.utc)),
        ),
    ]
