from .kanji import Itaiji as Itaiji
from .kanji import OConv as OConv
from .properties import Ch as Ch
from .scripts import IConv as IConv
from typing import Dict, List

class PyMerumException(Exception): ...
class UnknownCharacterException(PyMerumException): ...

class Merum:
    def __init__(self) -> None: ...
    def convert(self, text: str) -> List[Dict[str, str]]: ...
