# Generated by Django 4.2.5 on 2024-07-24 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_teammember_delete_signupreferrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccountServer',
            fields=[
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.billingaccount')),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookKey',
            fields=[
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.workspace')),
                ('key', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceCredentials',
            fields=[
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.workspace')),
                ('password', models.CharField(default=uuid.uuid4, max_length=255)),
            ],
        ),
    ]
