# Generated by Django 4.2.5 on 2024-07-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='group',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='webhookkey',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workspacecredentials',
            name='workspace',
        ),
        migrations.AlterUniqueTogether(
            name='workspacedestination',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workspacedestination',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='workspacedestination',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='BillingAccountServer',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='WebhookKey',
        ),
        migrations.DeleteModel(
            name='WorkspaceCredentials',
        ),
        migrations.DeleteModel(
            name='WorkspaceDestination',
        ),
    ]
