# Generated by Django 4.2.5 on 2024-07-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_workspaceevents_workspaceeventlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkspaceEvents',
            new_name='WorkspaceEvent',
        ),
        migrations.RenameModel(
            old_name='WorkspaceEventLogs',
            new_name='WorkspaceEventLog',
        ),
    ]
