# Generated by Django 4.2.5 on 2024-07-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0010_rename_workspace_id_workspaceevent_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPlatform',
            fields=[
                ('platform_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(max_length=255)),
                ('blend', models.BooleanField(default=False)),
                ('overall', models.BooleanField(default=False)),
                ('column_json', models.CharField(max_length=255)),
                ('app_only', models.BooleanField()),
                ('app2_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('credentials_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('credentials', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.allplatform')),
                ('api', models.CharField(max_length=255, unique=True)),
                ('account_list', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformOauth2Email',
            fields=[
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='oauth_user', serialize=False, to='db.credentials')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.platform')),
            ],
            options={
                'unique_together': {('platform', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PlatformOauth2',
            fields=[
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.platform')),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('redirect_uri', models.CharField(max_length=100)),
                ('options', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformJson',
            fields=[
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.credentials')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.platform')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_oauth_credentials', to='db.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUserOauth',
            fields=[
                ('platform_user_oauth_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_user', to=settings.AUTH_USER_MODEL)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user', to='db.platformoauth2email')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.platform')),
            ],
            options={
                'unique_together': {('platform', 'user')},
            },
        ),
    ]
