# Generated by Django 4.2.5 on 2024-08-05 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 9, 27, 29, 760587, tzinfo=datetime.timezone.utc)),
        ),
    ]
