# Generated by Django 5.0.6 on 2024-07-21 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stela_control', '0015_alter_billingrecipt_option_alter_company_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='bank',
            field=models.CharField(max_length=255, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_holder',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='billingrecipt',
            name='option',
            field=models.CharField(choices=[('budget_development', 'Budget Development'), ('budget_design', 'Budget Design'), ('Monthly charge', 'Monthly charge'), ('Billing receipt', 'Billing receipt'), ('budget_marketing', 'Budget Marketing'), ('Others', 'Others')], max_length=60, null=True, verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business',
            field=models.CharField(blank=True, choices=[('Media Creators', 'Media Creators'), ('Consulting', 'Consulting'), ('E-commerce', 'E-commerce'), ('Logistics and Transportation Services', 'Logistics and Transportation Services'), ('Beauty and Personal Care Services', 'Beauty and Personal Care Services'), ('Repair and Maintenance Services', 'Repair and Maintenance Services'), ('Restaurants and Food Services', 'Restaurants and Food Services'), ('Marketing and Advertising Services', 'Marketing and Advertising Services'), ('Health and Wellness', 'Health and Wellness'), ('Education and Training', 'Education and Training'), ('IT Development Services', 'IT Development Services')], max_length=100, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='card',
            field=models.CharField(blank=True, choices=[('card-tale', 'card-tale'), ('card-light-blue', 'card-light-blue'), ('card-light-danger', 'card-light-danger'), ('card-dark-blue', 'card-dark-blue')], max_length=50, null=True, verbose_name='Color Card'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, choices=[('Tutorials', 'Tutorials'), ('Interviews', 'Interviews'), ('Reviews', 'Reviews'), ('News', 'News'), ('Stories', 'Stories'), ('Events', 'Events')], default='News', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='fecade_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Youtube URL'),
        ),
        migrations.AlterField(
            model_name='facebookpagecomments',
            name='update_rate',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 23, 55, 23, 508653)),
        ),
        migrations.AlterField(
            model_name='invoicefile',
            name='control_id',
            field=models.CharField(max_length=255, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='invoicefile',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.CharField(choices=[('Style Template 3', 'Style Template 3'), ('Style Template 4', 'Style Template 4'), ('Style Template 2', 'Style Template 2'), ('Style Template 1', 'Style Template 1')], max_length=60, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.CharField(choices=[('Store', 'Store'), ('No Selected', 'No Selected'), ('Stela Marketing', 'Stela Marketing'), ('Cloud Domains', 'Cloud Domains'), ('Cloud Elastic Instance', 'Cloud Elastic Instance'), ('Stela Design', 'Stela Design'), ('Stela Websites', 'Stela Websites')], default='No Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='pathcontrol',
            name='step',
            field=models.CharField(choices=[('Step 2', 'Step 2'), ('Step 3', 'Step 3'), ('Step 4', 'Step 4')], default='No Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='retentionfile',
            name='control_id',
            field=models.CharField(max_length=255, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='retentionfile',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sitepolicy',
            name='section',
            field=models.CharField(blank=True, choices=[('Terms and Conditions', 'Terms and Conditions'), ('Cookie Policy', 'Cookie Policy'), ('Return Policy', 'Return Policy'), ('Disclaimer', 'Disclaimer'), ('Privacy Policy', 'Privacy Policy')], default='Terms and Conditions', max_length=150),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social',
            field=models.CharField(choices=[('X', 'X'), ('Instagram', 'Instagram'), ('Tiktok', 'Tiktok'), ('Youtube', 'Youtube'), ('Wikipedia', 'Wikipedia'), ('Github', 'Github'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin')], default='No Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxid',
            name='pdf_file',
            field=models.FileField(upload_to='taxID/', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='taxid',
            name='pdf_file2',
            field=models.FileField(blank=True, null=True, upload_to='taxID/', verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='business',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('Zelle', 'Zelle'), ('Paypal', 'Paypal'), ('Binance', 'Binance')], max_length=100, verbose_name='Type of Wallet'),
        ),
    ]
