
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-02T08:36:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bbc5279219fedbbc8f8a3b243ab7a344240a441",
 "version": "2024.08.05"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
