# coding: utf-8

"""
    Artifact Client API

    API for interacting with the Artifact Client.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from artifact_client.models.graph import Graph

class TestGraph(unittest.TestCase):
    """Graph unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Graph:
        """Test Graph
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Graph`
        """
        model = Graph()
        if include_optional:
            return Graph(
                uuid = '',
                organization_uuid = '',
                name = '',
                index_interval = '',
                host = '',
                status = '',
                node_count = 56,
                edge_count = 56
            )
        else:
            return Graph(
        )
        """

    def testGraph(self):
        """Test Graph"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
