class TokenBucket:
    def __init__(self, maxToken: int = 20, timePeriod: int = 30) -> None: ...
    @property
    def usetoken(self) -> bool: ...
    @property
    def maxToken(self) -> int: ...
    @maxToken.setter
    def maxToken(self, tokens: int) -> None: ...
    @property
    def timePeriod(self) -> int: ...
    @timePeriod.setter
    def timePeriod(self, seconds: int) -> None: ...
    @property
    def isEmpty(self) -> bool: ...
