# coding: utf-8

"""
    DeviceServer

    DeviceServer API  # noqa: E501

    The version of the OpenAPI document: 1.0.8
    Contact: david@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import DeviceServer
from DeviceServer.models.get_fan_speed200_response import GetFanSpeed200Response  # noqa: E501
from DeviceServer.rest import ApiException

class TestGetFanSpeed200Response(unittest.TestCase):
    """GetFanSpeed200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetFanSpeed200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = DeviceServer.models.get_fan_speed200_response.GetFanSpeed200Response()  # noqa: E501
        if include_optional :
            return GetFanSpeed200Response(
                fan_speed = 1.337
            )
        else :
            return GetFanSpeed200Response(
        )

    def testGetFanSpeed200Response(self):
        """Test GetFanSpeed200Response"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
