from typing import Any, Tuple, List, Optional


class Folder:
    folders: List[Tuple[str, Folder]]
    files: List[str]
    firstID: int
    def __init__(self, folders: Optional[List[Tuple[str, Folder]]] = ..., files: Optional[List[str]] = ..., firstID: int = ...) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __contains__(self, key): ...
    def idOf(self, path): ...
    def subfolder(self, path: str) -> Optional[Folder]: ...
    def filenameOf(self, id: int) -> str: ...

def load(fnt): ...
def save(root): ...
